[package]
name = "ristretto"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
sync = ["crossbeam"]
async = ["tokio", "tracing-futures", "futures"]

[dependencies.crossbeam]
version = "0.8"
optional = true

[dependencies.tokio]
version = "1.9.0"
features = ["full"]
optional = true

[dependencies.tracing-futures]
version = "0.2.5"
optional = true

[dependencies.futures]
version = "0.3"
optional = true

[dependencies]
anyhow = "1"
bytes = "1.0.1"
bincode = "1.3.3"
chrono = {version = "0.4.19", features = ["serde"]}
lazy_static = "1.4.0"
log = "0.4.14"
metrics = "0.16.0"
parking_lot = "0.11"
parse-display = "0.5.0"
serde_json = "1"
serde_yaml = "0.8"
serde = { version="1", features=["derive"] }
thiserror = "1"
tracing = "0.1.26"